### ISSUE TITLE
Ability to ignore some NOTEs in badges

### ISSUE THREAD

**Issue by sckott** [ropensci/cchecksapi#29]
via #28 

continuing conversation here

**Comment by sckott** [comment]
@gaborcsardi  

> I think we should just start easy, and ignore some, e.g. the one about the package size, for a start. If CRAN is OK with the NOTE, then the package author will be OK as well.

okay, makes sense

**Comment by maelle** [comment]
I was wondering whether it'd make sense to save the CRAN check state of each package right after release, if one assumes that at this point the checks should be ok. It could help identify NOTEs that are not important to put them in a general whitelist, or a list for each package (if we consider the check state of a package right after release is ok, then what the badge should show is whether things got _worse_?). 

By release I mean first release and release of a new version.

**Comment by gaborcsardi** [comment]
Unfortunately "right after release" is a but fuzzy, because some CRAN platform do not run the checks until somewhat later. Also, getting on CRAN  does not mean that it will work fine on all CRAN platforms. They only test on two platforms, Windows + R-devel and Debian/gcc  + R-devel. You might still get a failure on other Linuxes or Solaris.

**Comment by maelle** [comment]
I've just noticed the "worst" badge might be more informative than the "summary" badge since it's not binary.

**Comment by sckott** [comment]
right, not binary
